### ISSUE TITLE
A couple false positives in centos7-100 recipe

### ISSUE THREAD

**Issue by MattMencel** [chef-cookbooks/audit-cis#13]
I'm experimenting with Audit-CIS and noticed a couple items on my CentOS 7 host.

Is expect greedy in rspec?  It's failing on rule 3.9 (bind) when bind is not installed.   However there are several bind-libs and bind-utls packages that are installed.  Maybe it's greedy matching on those?

```
$ rpm -qa | grep -i bind
bind-license-9.9.4-18.el7_1.1.noarch
bind-libs-9.9.4-18.el7_1.1.x86_64
rpcbind-0.2.0-26.el7.x86_64
bind-utils-9.9.4-18.el7_1.1.x86_64
bind-libs-lite-9.9.4-18.el7_1.1.x86_64
```

Also 3.16, expect port 25 to be listening only on loopback.  That fails when no MTA is running.  Should the rule be expect port 25 to be listening only on loopback or not at all?

These are just a couple from my first quick look.

**Comment by jtimberman** [comment]
Hi @MattMencel! Thanks for reporting these issues.

For 3.9, that was a typo, and is fixed on master (commit cc497b1).

**Comment by jtimberman** [comment]
Oops, got overzealous on clicking the green comment button. I'll investigate 3.16.

**Comment by jtimberman** [comment]
Okay, got something I think will work. 

With postfix package removed, the service stopped:
```
Starting audit phase

3 Special Purpose Services
  4.16 Configure Mail Transfer Agent for Local-Only Mode
    listens on port 25 only on the loopback address

Finished in 0.10746 seconds (files took 0.35329 seconds to load)
1 example, 0 failures
Auditing complete

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 1.593586315 seconds
  1/1 controls succeeded
```

And with postfix package installed, and the service running:

```
Converging 0 resources
Starting audit phase

3 Special Purpose Services
  4.16 Configure Mail Transfer Agent for Local-Only Mode
    listens on port 25 only on the loopback address

Finished in 0.11943 seconds (files took 0.42219 seconds to load)
1 example, 0 failures
Auditing complete

Running handlers:
Running handlers complete
Chef Client finished, 0/0 resources updated in 1.686593884 seconds
  1/1 controls succeeded
```

**Comment by jtimberman** [comment]
There's some errors in the output but I assure you that master has the correct code :smile: :cake:
