### ISSUE TITLE
Ubuntu 14.04, 13.7 will always fail

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/audit-cis#14]
Background: https://gist.github.com/jtimberman/d60bc4ca49bd458336ac

The `libuuid` user will always exist on Ubuntu 14.04 because it is created in the postinst of the libuuid1 package, which is a dependency of several "essential" or "minimal install" packages.

**Comment by jtimberman** [comment]
Either we allow it in the control, or we note to users that this may be a problem that they need to resolve on their own.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
