### ISSUE TITLE
Use more robust regex to numeric comparison for password aging

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/audit-cis#15]
The checks for `PASS_MAX_DAYS` and `PASS_MIN_DAYS` use regular expressions. These should use regex groups to match the digits, and then use the appropriate comparison operators. E.g.,

```ruby
match(/PASS_MAX_AGE\s+\b(\d.*)\b/)
expect($1.to_i).to be >= 90
```

**Comment by jtimberman** [comment]
This is in the centos recipe(s).

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
