### ISSUE TITLE
Consider use of RSpec implicit subjects

### ISSUE THREAD

**Issue by aaron-lane** [chef-cookbooks/audit-cis#17]
Using RSpec's implicit subject style could help clean up the control bodies:

```ruby
control '8.2.3 Configure /etc/rsyslog.conf' do
  it 'has common log files and syslog facilities configured in /etc/rsyslog.conf' do
    expect(file('/etc/rsyslog.d/50-default.conf').content).to contain('/var/log/auth.log')
    #...
  end
end
```

```ruby
control '8.2.3 Configure /etc/rsyslog.conf' do
  describe file '/etc/rsyslog.d/50-default.conf' do
    its(:content) { is_expected.to contain '/var/log/auth.log' }
    #...
  end
end
```

**Comment by jtimberman** [comment]
While the implicit subject style is cleaner, auditing is a very specific and explicitly defined thing. It's more verbose to type, surely, but we've already done that for you:

```
% grep -c 'it .*do' recipes/*-*rb
recipes/centos6-110.rb:222
recipes/centos7-100.rb:216
recipes/ubuntu1404-100.rb:225
```

663 times, in fact. We don't plan to rewrite:

```
% wc -l recipes/*-*.rb
    1348 recipes/centos6-110.rb
    1324 recipes/centos7-100.rb
    1675 recipes/ubuntu1404-100.rb
    4347 total
```

The former style is also how we've documented things in the [audit mode documentation](https://docs.chef.io/analytics.html#audit-mode).

**Comment by jtimberman** [comment]
Update:

While discussing this in an internal discussion, it was also noted that RSpec 3 deprecated the `should` syntax, and we disable it in Chef's audit mode. However if it is working (and it was when I tested it), that's a bug in Chef that we need to fix. The `expect` syntax as used in this cookbook is correct.
