### ISSUE TITLE
Move contexts and controls and their checks around to line up output nicer

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/audit-cis#2]
The hierarchy of the control_group, control, and it blocks aren't consistently lined up. It's probably best if each actual check has a separate control, with multiple `it` blocks to validate that specific control.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
