### ISSUE TITLE
Numerous checks are incorrect in ubuntu 14.04

### ISSUE THREAD

**Issue by e100** [chef-cookbooks/audit-cis#21]
I've submitted two pull requests that fix multiple incorrect tests in the ubuntu 14.04 tests.

1.1 check was incorrect resulting in failure if updates existed or not
https://github.com/chef-cookbooks/audit-cis/pull/18

3.2 check was incorrect according to CIS benchmark
8.1.1.1-3  always failed due to missing .content
8.1.6 check for /etc/network was incorrect
https://github.com/chef-cookbooks/audit-cis/pull/20

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
