### ISSUE TITLE
Control 12.10 and 12.11 does not conform to the CIS benchmark

### ISSUE THREAD

**Issue by e100** [chef-cookbooks/audit-cis#23]
The controls are written to not allow any SUID or SGID binaries, this is incorrect.

The CIS benchmark for Ubuntu 14.04 states:
"Ensure that no **rogue** set-UID programs have been introduced into the system. Review the
files returned by the action in the Audit section and confirm the integrity of these binaries."

My suggestion is to allow users to specify some attributes defining a list of allowed binaries along with checksums. 

If unlisted binaries are found or if checksums of binaries do not match then the control should fail.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
