### ISSUE TITLE
Need ability to enable/disable individual tests

### ISSUE THREAD

**Issue by lamont-granquist** [chef-cookbooks/audit-cis#24]
Filtering in analytics is not delightful:

* output on the command line is messy with lots of failing tests that just need to 'be ignored'
* failed tests result in an overall failed chef-client run, so with failing audit tests you can't run them automatically with chef-client or the runs fail
* the chef-client has knowledge like "is a DNS server" which can be used to turn off checks like "should not be listening on port 53" -- which is easier to get right in code on the client than to keep analytics rules in sync with client config.

**Comment by e100** [comment]
I agree with @lamont-granquist 

Not having a simple method to enable/disable individual tests limits the usefulness of this cookbook.

**Comment by lamont-granquist** [comment]
I can update this with a concrete use case as well:

As an Audit/Compliance Person,
I want to be able to check that port 53 is not listening on all servers that are not supposed to be DNS servers,
So that I can get notification of possible security holes and issues caused by rogue DNS servers.

So if the cookbook that managed the DNS servers set some kind of flag one way or another (please not hardcoded inflexible roles or attributes) that the server was supposed to run DNS, then the chef-client run itself could turn off the 'should not be listening on port 53' and 'should not have bind in the process table' kinds of tests.  Everything else in your infrastructure would run and report on that.  When new DNS servers were deployed then it would be automatically get the rules correct.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
