### ISSUE TITLE
Control 4.5 for Ubuntu 14.04 does not conform to CIS benchmark

### ISSUE THREAD

**Issue by e100** [chef-cookbooks/audit-cis#26]
The CIS benchmark says to check that profiles are loaded and non of them are in complain mode.
It also states that no process should be unconfined.

The output of "aa-status" provides this information.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
