### ISSUE TITLE
Control 4.5 for Ubuntu 14.04 service checks always fail

### ISSUE THREAD

**Issue by e100** [chef-cookbooks/audit-cis#27]
apparmor is not a "service", the init script simply loads/unloads profiles into the kernel. There is no running daemon.

The "is running apparmor service" check always fails and is redundant anyway since "has apparmor loaded" is sufficient to check that apparmor was "started."

"enables the apparmor service" always fails even with the service enabled.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
