### ISSUE TITLE
Control 2.25 Fix

### ISSUE THREAD

**Issue by jsmickey** [chef-cookbooks/audit-cis#29]
2.25 Disable Automounting

initctl output goes to stderr instead of stdout, need to update test

**Comment by jsmickey** [comment]
@binamov We met at reInvent, I would like to help manage this cookbook, let me know how I can help

**Comment by binamov** [comment]
@jsmickey I chatted with @jtimberman and he will retain maintainership of this cookbook. We'll approve PRs as our capacity permits. If this is a pressing issue, you're probably better off running your fork.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
