### ISSUE TITLE
create a test cookbook that performs remediation

### ISSUE THREAD

**Issue by jtimberman** [chef-cookbooks/audit-cis#3]
For test kitchen purposes, it would be nice to have a test cookbook that implements remediation of everything. This may also require a special box to use that has the recommended disks created, but for now those portions of the benchmark are out of scope for this cookbook.

**Comment by tas50** [comment]
This cookbook has been deprecated. At this time I'm going to close this issue out. I'm sorry that we never brought it to a full resolution prior to the deprecation
